\documentclass{beamer}
\usepackage[utf8]{inputenc}
\usepackage{polski}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{natbib}
\usepackage{graphicx}
\usepackage{array,booktabs,tabularx}
\usepackage{epstopdf}
\usepackage{colortbl, xcolor}
\usepackage{url}

\usetheme{Dresden}

\title{AmyloGram 2.0: MBO in the prediction of amyloid proteins}
\date{}
\author{Dominik Rafacz}
\institute{Warsaw University of Technology}

\begin{document}

\maketitle
\begin{frame}{Amyloidogenic proteins}
  \begin{figure} 
    \includegraphics[width=0.75\textwidth]{figures/amyloid_aggregates.jpg}
  \end{figure}
  
  \footnotesize
  Amyloid aggregates (red) around neurons (green). Strittmatter Laboratory, Yale University.
\end{frame}


\begin{frame}{AmyloGram - n-grams analysis}
  \begin{figure} 
    \includegraphics[width=0.95\textwidth]{figures/ngram1.eps}
  \end{figure}
  
  Example 1-grams: A, L, G \\
  Example 2-grams: AL, MM, MY \\
  Example 2-grams (with a gap): A-L, M-M, M-Y
  
  \begin{tiny}
    Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961 \\
  \end{tiny}
\end{frame} 


\begin{frame}{AmyloGram - alphabet reduction}
  \begin{figure} 
    \includegraphics[width=0.95\textwidth]{figures/ngram3.eps}
  \end{figure}

  \tiny{Burdukiewicz, M., Sobczyk, P., Rödiger, S., Duda-Madej, A., Mackiewicz, P., and Kotulska, M. (2017). Amyloidogenic motifs revealed by n-gram analysis. Scientific Reports 7, 12961}
\end{frame}


\begin{frame}{MBO}

<<r,warning=FALSE,message=FALSE,echo=FALSE,include=TRUE,fig.height=4.5,results = "hide">>=
library(ggplot2)
library(mlrMBO)
library(mlr)
library(randomsearch)
library(paramtest)
library(gridExtra)

present_theme <- theme_bw(base_size = 12) +
  theme(legend.position = "bottom", 
        plot.background = element_rect(fill = NA, color = NA), 
        legend.background= element_rect(fill = NA))

set.seed(1590)
fn2 = makeSingleObjectiveFunction(
  name = "Sample Function",
  fn = function(x) sin(x)*x^2,
  par.set = makeNumericParamSet("x", len = 1L, lower = -3.8L, upper = 2L),
  global.opt.params = list(x = 0)
)
ctrl = makeMBOControl(propose.points = 1)
ctrl = setMBOControlTermination(ctrl, iters = 6L)
ctrl = setMBOControlInfill(ctrl, crit = makeMBOInfillCritEI(),
                           opt = "focussearch", opt.focussearch.points = 500L)
run <- exampleRun(fn2, control = ctrl)

df <- as.data.frame(run$mbo.res$opt.path) 
g1 <- ggplot(data=run$evals, aes(x=x,y=y)) + geom_line() + geom_point(data=data.frame(x=df$x,y=df$y)) + 
  geom_point(data=data.frame(x=run$mbo.res$x,y=run$mbo.res$y), color="red") +
  geom_text(data=data.frame(x=run$mbo.res$x,y=run$mbo.res$y), label = round(run$mbo.res$y, 2), color="red", vjust = -1) +
  ggtitle("MBO") +
  present_theme

runRandomSearch <- randomsearch(fn2, max.evals = 10L)
df2 <- as.data.frame(runRandomSearch)
opt2 <- getOptPathEl(runRandomSearch, index = getOptPathBestIndex(runRandomSearch))
g2 <- ggplot(data=run$evals, aes(x=x,y=y)) + geom_line() + geom_point(data=data.frame(x=df2$x,y=df2$y)) + 
  geom_point(data=data.frame(x=opt2$x,y=opt2$y), color="red") +
  geom_text(data=data.frame(x=opt2$x,y=opt2$y), label = round(opt2$y, 2), color="red", vjust = -1) +
  ggtitle("Random search") +
  present_theme


fn2.b <- function(iter, x) return(sin(x)*x^2);
runGridSearch <- grid_search(fn2.b, params = list(x=seq(-3.8,2)))
df3 <- data.frame(x=runGridSearch$tests$x, y=unlist(runGridSearch$results))
opt3 <- data.frame(x=runGridSearch$tests$x[which.min(unlist(runGridSearch$results))],y=min(unlist(runGridSearch$results)))
g3 <- ggplot(data=run$evals, aes(x=x,y=y)) + geom_line() + geom_point(data=data.frame(x=df3$x,y=df3$y)) + 
  geom_point(data=data.frame(x=opt3$x,y=opt3$y), color="red") +
  geom_text(data=data.frame(x=opt3$x,y=opt3$y), label = round(opt3$y, 2), color="red", vjust = -1) +
  ggtitle("Grid search") +
  present_theme

grid.arrange(g3, g2, g1, ncol = 1)
@

\end{frame} 

\begin{frame}{Results}
<<res,warning=FALSE,message=FALSE,echo=FALSE,include=TRUE,fig.height=3.5,results = "hide">>=
results <- readr::read_csv("results/all_models_scores.csv")

library(tidyverse)
results %>%
  select(-pos, -nice_name, -X1, -MCC) %>%
  filter(classifier %in% c("full_alphabet", "best_alphabet", 
                           "class14596_10", "raw_aa_10",
                           "PASTA2", "appnn", "FoldAmyloid")) %>%
  mutate(classifier = fct_reorder(fct_recode(as.factor(classifier), 
                              `AmyloGram 2.0 full\n alphabet` = "full_alphabet",
                              `AmyloGram 2.0 best\n alphabet` = "best_alphabet",
                              `AmyloGram full\n alphabet` = "raw_aa_10",
                              `AmyloGram best\n alphabet` = "class14596_10"),
                              1:7)) %>%
  gather(colname, value, -classifier) %>%
  group_by(colname) %>%
  mutate(maxcol = max(value)) %>%
  ungroup() %>%
  ggplot(aes(x = colname, y = classifier, fill = value,
             colour = as.factor(ifelse(value == maxcol, 1, 2)))) +
  geom_bin2d(stat = "identity", color = "black") +
  geom_text(aes(label = format(value, digits = 4))) +
  scale_color_manual(values = c("red", "black"), guide = FALSE) +
  scale_fill_distiller(palette = "YlOrBr") +
  theme_minimal() +
  xlab("measure") +
  ylab("classifier") +
  ggtitle("Scores of classifiers")
@
Features used in the model with full alphabet: \textbf{33620} \\
Features used in the model with best alphabet: \textbf{1014}


\end{frame} 

\begin{frame}{Acknowledgements}

\end{frame} 

\begin{frame}{References}

\end{frame} 
\end{document}